<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-HTG9NIC3" failures="1" tests="9" name="Test" time="125.224" errors="0" timestamp="17 Sept 2025 14:19:03 GMT">
  <testcase classname="testCases.TC002_VerifyHomePageTabs" name="verifytopmenu" time="6.357"/>
  <testcase classname="testCases.TC003_VerifyFooterLinks" name="verifyfooter" time="8.337">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Twitter is broken with response code 403 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Twitter is broken with response code 403 expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at pageObjects.HomePage.verifyLinkBroken(HomePage.java:73)
at testCases.TC003_VerifyFooterLinks.verifyfooter(TC003_VerifyFooterLinks.java:15)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyfooter -->
  <testcase classname="testCases.TC004_SearchItem" name="searchitem" time="3.938"/>
  <testcase classname="testCases.TC004_SearchItem" name="searchitem" time="3.865"/>
  <testcase classname="testCases.TC004_SearchItem" name="searchitem" time="2.735"/>
  <testcase classname="testCases.TC004_SearchItem" name="searchitem" time="4.489"/>
  <testcase classname="testCases.TC005_FilterProductByPrice" name="filterproduct" time="1.449"/>
  <testcase classname="testCases.TC006_SortProductByPriceLowToHigh" name="filterproductlowtohigh" time="2.641"/>
  <testcase classname="testCases.TC007_EmptySearchAlert" name="verifyemptysearchalert" time="0.261"/>
</testsuite> <!-- Test -->
